In [60]:
import pandas as pd
import re

## Read data

In [15]:
influ = pd.read_csv(r"C:\Users\marle\Files\programowanie\Influencer_Selection\GNN-IR\data\influencer_info.csv")

In [21]:
influ.duplicated(subset='influencer').sum()

0

In [24]:
79082010/804000

98.36070895522388

In [22]:
influ

,Unnamed: 0,influencer,keyword,ad_name,subscribers,num_videos,view,clear_subscriber,clear_video,clear_view,average_view,negative,positive
0,0,areumsongee아름송이,뷰티 & 메이크업 & 패션 & 뷰티,"['나의 결혼계획 발표...타투소개 , 30대의 노화관리(?) 그리고 스무살 송충이...",구독자 80.4만명,266,"조회수 79,082,010회",804000,266,79082010,98.360709,0.165041,0.834959
1,1,솔업 sollup,패션 & 뷰티 & 코디 & 룩북,['아트가 라이프에 주는 가치에 대해? 아트 컬렉팅을 시작하는 쉬운 방법 공유해요!...,구독자 5.67만명,126,"조회수 3,560,810회",56700,126,3560810,62.800882,0.126663,0.873337
2,2,에익쿠,만화 & 애니메이션 & 언어,"['ENG) 첫 임무 / MBTI 저승사자 만화 ep.3', 'MBTI 올리브영 할...",구독자 33.1만명,176,"조회수 77,560,785회",331000,176,77560785,234.322613,0.264321,0.735679
3,3,마빡,게임 & 음식,['경북 성주로 밀웜사육하는곳가서 직접먹방!! [ Mealworm Mukbang ]...,구독자 14.6만명,2.2천,"조회수 47,977,810회",146000,2200,47977810,328.615137,0.434274,0.565726
4,4,nbkorea,패션 & 뷰티 & 스포츠 의류,['[뉴발란스] New Balance Womens Sports Club with 뉴...,구독자 6.95천명,481,"조회수 16,441,242회",6950,481,16441242,2365.646331,0.032029,0.967971
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3807,3807,핵꿀잼,"영화 & 교육 & 직업, 언어","['드라마 아니고 영환줄..', '미친 삼각 말아주는 #최악의악', '유재석이 기다...",구독자 16.6만명,1.3천,"조회수 878,905,265회",166000,1300,878905265,5294.610030,0.811188,0.188812
3808,3808,지식인사이드,"의료 & 건강, 신체 질환 & 컨디션 이상 & 재테크","[""EBS 명의 출연 정형외과 전문의, 제 부모님이 무릎 아프다고 하시면 딱 '이것...",구독자 117만명,410,"조회수 194,240,972회",117000,410,194240972,1660.179248,0.316265,0.683735
3809,3809,흥삶이네 Heungsam's Life,식품 & 먹방 & 레시피,"['부모님 모시고 홍천 한우 먹고왔습니다.', '부모님 모시고 군산에 다녀왔습니다....",구독자 6.49만명,27,"조회수 7,276,901회",64900,27,7276901,112.124823,0.270422,0.729578
3810,3810,리뷰하는고래,"IT & 전자기기, 소비자 가전 & 취미 & 공예, 특별한 날","['""왜 안춥지?"" 난방비 절약하는 겨울 꿀템 추천 제품 5가지', '갤럭시도 맥세...",구독자 1.43만명,93,"조회수 18,304,358회",14300,93,18304358,1280.025035,0.520805,0.479195
3811,3811,공간일기,헤어 케어 & 식품,"['거북목 필수 시청! 수면의 질 확 올리는 베개🐰\U0001fa75', '삶의 질...",구독자 8.25만명,174,"조회수 46,139,028회",82500,174,46139028,559.260945,0.795177,0.204823

In [25]:
adv = pd.read_csv(r"C:\Users\marle\Files\programowanie\Influencer_Selection\GNN-IR\data\advertiser_influencer_link.csv")

## Clean columns

In [48]:
adv['view'] = adv['view'].str.replace('조회수', '').str.strip()

In [59]:
adv['symbol'] = adv['view'].str.replace(r'[0-9.,\s]', '', regex=True)

In [57]:
adv['view'].str.replace(r'[0-9.,\s]', '', regex=True).value_counts()

view
K     22707
M      1096
        944
만       313
천        95
백만       19
Name: count, dtype: int64

In [67]:
def parse_views(value):
    if 'K'in value or '천' in value:
        multiplier = 1000
    elif 'M' in value or '백만' in value:
        multiplier = 1000000
    elif '만' in value:
        multiplier = 10000
    else:
        multiplier = 1
    return int(float(re.sub(r'[^0-9.,\s]', '', value)) * multiplier)

In [62]:
test_values = ['3K', '4만', '1.5M', '2백만', '250', '3.5천']

for value in test_values:
    print(value, parse_views(value))

3K 3000.0
4만 40000.0
1.5M 1500000.0
2백만 2000000.0
250 250.0
3.5천 3500.0

In [68]:
adv = adv.assign(
    views_numeric = adv['view'].apply(parse_views)
)

In [69]:
adv

,Unnamed: 0,title,advertiser,influencer,date,view,keyword,videoID,symbol,views_numeric
0,0,현 올영알바가 추천하는 향수대신 쓰기 좋은 갓성비 향기템 추천 #올리브영알바 #올영...,더블유드레스룸,유나러부,23.08.26,3K,뷰티 & 메이크업,VW5HM-wVV08,K,3000
1,1,"3배 더 예뻐지는 ""컨투어링"" 멱살 잡고 알려드림✊? | 죽어가는 이목구비 소생법 ...",페리페라,지냐 Jinyaa,23.08.26,73K,뷰티 & 메이크업,wCjzu3OT2XE,K,73000
2,2,갸루 언니✌ to K-아이돌?언니 데뷔해줘요,에뛰드,회사원A,23.08.26,32K,뷰티 & 메이크업,T8PLbhE6fqc,K,32000
3,3,토너 200% 활용법 #토너팩하는법 #더마펌,더마펌,랏뚜 Beauty,23.08.26,51,뷰티 & 메이크업,olFCmnJ-znY,,51
4,4,베네피트 신상틴트? 태연PICK 6컬러 발라보기! (스플래시 듀이틴트&플러시 벨벳틴...,베네피트,HANE 하네,23.08.26,3K,뷰티 & 메이크업,_y9BEWs3obc,K,3000
...,...,...,...,...,...,...,...,...,...,...
25169,25169,이런거까지 된다는 요즘 로봇청소기 ㄷㄷ,아이리버,공간일기,23.08.28,8천,IT & 전자기기,dDwK_uvlqh0,천,8000
25170,25170,미리보는 남자 가을코디 (with 갤럭시 Z 플립5),삼성전자,코디메이커 피로,23.08.27,4만,IT & 전자기기,6ugZ1JO600o,만,40000
25171,25171,"ENG) 다이노탱 때문에 백화점 오픈런이라는걸 해봄😱 귀여운 마그넷 만들고, 콩알이...",삼성전자,코지데이 CozyDay,23.08.27,2만,IT & 전자기기,HHUiqWBWcoA,만,20000
25172,25172,손 그림 VS 액정 타블렛 ? 뉴진스 하니,엑스피펜,MerryMa 메리마,23.08.26,1백만,IT & 전자기기,-0JNe3se7JM,백만,1000000
25173,25173,갤럭시 탭 S9으로도 유화 그릴 수 있음,삼성전자,쥬캔버스 JOO CANVAS,23.08.26,3만,IT & 전자기기,McEhiA9oZhc,만,30000

In [34]:
adv.groupby(['advertiser', 'influencer']).size().reset_index().sort_values(0, ascending=False)

      advertiser        influencer    0
4337        리니지M                 렌  623
4339        리니지M                무티  567
4347        리니지M                카라  343
4336        리니지M                도건  336
4354        리니지W            똘끼100%  274
...          ...               ...  ...
5411         미쟝센      아르몽Ahrumongg    1
5412         미쟝센             안녕하세미    1
5413         미쟝센  엔조이커플enjoycouple    1
5414         미쟝센           이응oioio    1
14906         힘펠    댄나 프로젝트, 집꾸며볼래    1

[14907 rows x 3 columns]

In [70]:
df = adv.merge(influ, how='inner', on='influencer')

In [73]:
df.head(1)

,Unnamed: 0_x,title,advertiser,influencer,date,view_x,keyword_x,videoID,symbol,views_numeric,...,ad_name,subscribers,num_videos,view_y,clear_subscriber,clear_video,clear_view,average_view,negative,positive
0,0,현 올영알바가 추천하는 향수대신 쓰기 좋은 갓성비 향기템 추천 #올리브영알바 #올영...,더블유드레스룸,유나러부,23.08.26,3K,뷰티 & 메이크업,VW5HM-wVV08,K,3000,...,['현 올영알바가 추천하는 세일 때 안 보고가면 후회하는 극강의 진정*보습템 추천 ...,구독자 9.75천명,79,"조회수 8,434,363회",9750,79,8434363,865.062872,0.219607,0.780393

In [86]:
final_df = df.groupby(['advertiser', 'influencer']).agg(
    n_videos=('videoID','nunique'),
    median_views=('views_numeric','median'),
    median_min=('views_numeric','min'),
    median_max=('views_numeric','max'),
).reset_index()

In [87]:
final_df

,advertiser,influencer,n_videos,median_views,median_min,median_max
0,러쉬로얄,겜브링 GGAM BRING,1,57000.0,57000,57000
1,러쉬로얄,깨박이,1,14000.0,14000,14000
2,러쉬로얄,킴성태TV,1,63000.0,63000,63000
3,1664 블랑,피치림 Peach Rim,1,304000.0,304000,304000
4,1943,K-현실고증,1,250000.0,250000,250000
...,...,...,...,...,...,...
14902,힘난다,고기남자 MeatMan,1,2700000.0,2700000,2700000
14903,힘난다,둥이키친 DUNGYIKITCHEN,1,9000.0,9000,9000
14904,힘난다,요리용디 Yori Yongd,5,870000.0,519000,1300000
14905,힘펠,가봄TV / gabomTV,1,6000.0,6000,6000
14906,힘펠,"댄나 프로젝트, 집꾸며볼래",1,641000.0,641000,641000